### ISSUE TITLE
Kanban Board Done

### ISSUE THREAD

**Issue by Juanse7793** [Juanse7793/Recipe-app#14]
Hi dear reviewer in this team we are 2 people @isaacpitwa and myself @Juanse7793 

this is the link to our Kanban Board

[Link](https://github.com/users/Juanse7793/projects/1)

**Comment by sja-thedude** [comment]
## Invalid Code Review Request ❌

Hi Team, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a valid link to github project. Also you have not set up your kanban board make sure to do it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete! 🍾🚢 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks
- Good descriptive board title and description of task

<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
